version: "3.9"

name: webhooks-debug

services:
  cf-tunnel-webhooks-debug:
    restart: unless-stopped
    container_name: "cf-tunnel-webhooks-debug"
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMDUxOWQ3YzU3ODhiNTM2ZGZlZDRmNTVjYWNjYTM2YjEiLCJ0IjoiZGUyMTlhOTAtY2M4MC00YTUzLWJkZjctMTQwNGRlNGFjNzhmIiwicyI6Ik56WXpaRGd4TWpjdFpUTmhZaTAwTURReUxUZzRZVEl0WWpFeU5XTXlPRFJqTTJFNSJ9

  webhooks:
    container_name: webhooks-debug
    image: webhooks-debug:latest
    platform: linux/amd64
    build:
      context: .
      args:
        INSTALL_DEBUGGER: true
    ports:
      - 8085:8085
      - 5678:5678
    volumes:
      - ./app:/app/app
      - ./interface:/app/interface
      - ./logs:/app/logs
      # - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .local.env
    command: >
      sh -c "python3 -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn interface.web.main:create_app --reload --host 0.0.0.0 --port 8085"
